"""Read the shipped record of which Houdini versions have been sampled.

``data/sampled_versions.json`` is generated by ``tools/gen_node_versions.py``
from the Houdini builds contributors have sampled. Only the version list ships;
the full per-node evidence stays in ``tools/node_versions.json``, which is a
megabyte nothing at runtime needs. The instructions in
``prompts/markdown/server_instructions.md`` carry version markers derived from
it, e.g. ``colorcorrect (21.0+)``.

Those markers cannot know about a Houdini nobody has sampled yet. Read literally
``(21.0+)`` includes a future 23.0, so if SideFX drops a node there the way they
dropped the LOP ``layout`` in 22.0, the instructions would keep advertising it.
This module exists so the server can notice that case and say so, rather than
letting a stale marker pass silently. It is a staleness signal, not a
correctness mechanism: ``build_network(dry_run=True)`` validates node types
against the running Houdini and cannot go out of date.
"""

from __future__ import annotations

# Built-in
import json
import logging
from functools import lru_cache
from pathlib import Path

logger = logging.getLogger(__name__)

_TABLE = Path(__file__).parent / "data" / "sampled_versions.json"


@lru_cache(maxsize=1)
def load_table() -> dict:
    """Return the shipped table, or empty structures when it is unreadable.

    Never raises: a missing or corrupt table degrades this to "no opinion",
    which is the right outcome for a diagnostic that must not break a session.
    """
    try:
        table = json.loads(_TABLE.read_text(encoding="utf-8"))
    except FileNotFoundError:
        logger.debug("No sampled-version record shipped at %s", _TABLE)
        return {"builds": {}, "series": []}
    except (OSError, json.JSONDecodeError) as exc:
        logger.warning("Could not read the sampled-version record: %s", exc)
        return {"builds": {}, "series": []}

    table.setdefault("builds", {})
    table.setdefault("series", [])
    return table


def series_of(version: str | None) -> str | None:
    """Reduce "22.0.368" to its minor series "22.0".

    Returns None for anything that does not start with two integer components,
    which is what the health endpoint reports when it cannot determine a version.
    """
    if not version:
        return None
    parts = version.split(".")
    if len(parts) < 2:
        return None
    try:
        return f"{int(parts[0])}.{int(parts[1])}"
    except ValueError:
        return None


def sampled_series() -> list[str]:
    """Minor series the table has evidence for, oldest first."""
    table = load_table()
    series = set(table.get("series") or []) | set(table["builds"].values())
    return sorted(series, key=lambda s: tuple(int(p) for p in s.split(".")))


def staleness_warning(version: str | None) -> str | None:
    """Return a warning when *version* is outside what has been sampled.

    None means the version is covered and the markers can be trusted. Callers
    should treat any string as advisory, not as an error.
    """
    known = sampled_series()
    if not known:
        return None  # No table shipped; nothing to be stale about.

    series = series_of(version)
    if series is None or series in known:
        return None

    covered = ", ".join(known)
    key = tuple(int(part) for part in series.split("."))
    newest = tuple(int(part) for part in known[-1].split("."))
    if key > newest:
        return (
            f"Houdini {series} is newer than any version this build has data for "
            f"({covered}). Node-type version markers in the instructions may be "
            f"stale: a node listed without a range, or with a range ending "
            f"'+', is assumed to still exist here and may not. Verify with "
            f"list_node_types or build_network(dry_run=True)."
        )
    return (
        f"Houdini {series} is older than any version this build has data for "
        f"({covered}). Node-type version markers in the instructions do not "
        f"describe it; verify names with list_node_types."
    )
