"""Generate the node vocabulary tables in the workflow prompt markdown.

The workflow prompts advertise node names too, and until now they did it by
hand. That is the same hazard server_instructions.md was generated to remove:
usd_scene_assembly.md offered the LOP ``payload``, which is not a node type, and
simulation_setup.md offered ``bulletsolver``, which no sampled build has.

    python tools/gen_prompt_vocab.py            # regenerate
    python tools/gen_prompt_vocab.py --check    # fail if stale or invalid

Why this is a second generator rather than more of gen_node_domains.py: that one
groups by SideFX ``#tags``, which only SOPs carry in useful numbers (66% of
pages, against 19% for LOPs, and ``materiallibrary`` carries none). The tag path
therefore cannot express "the LOP nodes a lookdev task needs". So the grouping
lives in tools/prompt_vocab.json as an editorial decision, and this script
supplies what a person should not be trusted with: whether each name exists, and
in which versions.

Validation reads tools/node_versions.json only, never a local Houdini. That
keeps ``--check`` deterministic and runnable in CI, and it is also more correct
than checking the newest install: ``Lop/instancer`` is absent from 22.0 and
still needs advertising to 20.5 and 21.0 users, annotated.
"""

from __future__ import annotations

# Built-in
import argparse
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
_MD_DIR = REPO_ROOT / "python" / "fxhoudinimcp" / "prompts" / "markdown"
_VOCAB = Path(__file__).resolve().parent / "prompt_vocab.json"
_TABLE = Path(__file__).resolve().parent / "node_versions.json"

sys.path.insert(0, str(Path(__file__).resolve().parent))

# Reused so the version syntax cannot drift between the two generators, and so
# "present in a series" keeps meaning "every sampled build of that series had
# it" rather than a second, looser definition living here.
from gen_node_domains import deprecated_names  # noqa: E402
from gen_node_versions import annotation_for, availability  # noqa: E402


def _begin(marker: str) -> str:
    return f"<!-- BEGIN GENERATED: {marker} -->"


def _end(marker: str) -> str:
    return f"<!-- END GENERATED: {marker} -->"


def _resolve(
    name: str,
    contexts: list[str],
    per_series: dict[str, dict[str, bool]],
) -> tuple[str, str] | None:
    """Return (key, context) for the first context that ever had this name.

    Versioned type names are matched on their base: SideFX ships the Boolean SOP
    as ``boolean::2.0`` while ``boolean`` is what create_node takes, and
    rejecting the unversioned spelling would reject the spelling that works.
    """
    for context in contexts:
        exact = f"{context}/{name}"
        if exact in per_series:
            return exact, context
        versioned = sorted(key for key in per_series if key.startswith(f"{context}/{name}::"))
        if versioned:
            return versioned[0], context
    return None


def render_block(
    block: dict,
    series: list[str],
    per_series: dict[str, dict[str, bool]],
    deprecated: set[str],
) -> tuple[str, list[str]]:
    """Return (markdown table, problems)."""
    problems: list[str] = []
    contexts = block["contexts"]
    headers = block["headers"]

    lines = [
        "Generated by `tools/gen_prompt_vocab.py` from tools/prompt_vocab.json.",
        "Do not hand-edit: edit that file and regenerate.",
        "",
        "A name with a version range exists only in those versions of the",
        "20.5-22.0 range this server supports. Unannotated names exist",
        "throughout. Check `get_scene_info` before relying on an annotated name.",
        "",
        "| " + " | ".join(headers) + " |",
        "|" + "|".join("---" for _ in headers) + "|",
    ]

    for row in block["rows"]:
        if len(row["cells"]) != len(headers) - 1:
            problems.append(
                f"{block['file']}/{block['marker']}: row {row['label']!r} has "
                f"{len(row['cells'])} cells, headers want {len(headers) - 1}"
            )
            continue
        rendered = []
        for cell in row["cells"]:
            names = []
            for name in cell:
                found = _resolve(name, contexts, per_series)
                if found is None:
                    problems.append(
                        f"{block['file']}/{block['marker']}: "
                        f"{'/'.join(contexts)}/{name} is in no sampled build"
                    )
                    continue
                key, _ = found
                if key in deprecated:
                    problems.append(
                        f"{block['file']}/{block['marker']}: {key} is deprecated "
                        "in the newest sampled build"
                    )
                    continue
                mark = annotation_for(per_series[key], series)
                names.append(f"{name} {mark}" if mark else name)
            rendered.append(", ".join(names))
        lines.append(f"| {row['label']} | " + " | ".join(rendered) + " |")

    return "\n".join(lines), problems


def inject(text: str, marker: str, block: str) -> str | None:
    begin, end = _begin(marker), _end(marker)
    if begin not in text or end not in text:
        return None
    start = text.index(begin) + len(begin)
    stop = text.index(end)
    return text[:start] + "\n" + block + "\n" + text[stop:]


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if stale")
    args = parser.parse_args()

    if not _TABLE.is_file():
        print(f"{_TABLE.relative_to(REPO_ROOT)} is missing. Run tools/gen_node_versions.py first.")
        return 1

    table = json.loads(_TABLE.read_text(encoding="utf-8"))
    vocab = json.loads(_VOCAB.read_text(encoding="utf-8"))
    series, per_series = availability(table)
    deprecated = deprecated_names(table)

    problems: list[str] = []
    updates: dict[Path, str] = {}
    stale: list[str] = []

    for block in vocab["blocks"]:
        path = _MD_DIR / block["file"]
        if not path.is_file():
            problems.append(f"{block['file']} does not exist")
            continue
        rendered, issues = render_block(block, series, per_series, deprecated)
        problems.extend(issues)

        text = updates.get(path, path.read_text(encoding="utf-8"))
        updated = inject(text, block["marker"], rendered)
        if updated is None:
            problems.append(
                f"{block['file']}: markers missing\n"
                f"    {_begin(block['marker'])}\n    {_end(block['marker'])}"
            )
            continue
        if updated != text:
            stale.append(f"{block['file']} [{block['marker']}]")
        updates[path] = updated

    print(f"series      : {', '.join(series)}")
    print(f"blocks      : {len(vocab['blocks'])}")
    print(
        f"names       : {sum(len(c) for b in vocab['blocks'] for r in b['rows'] for c in r['cells'])}"
    )

    if problems:
        print(f"\n{len(problems)} problem(s):")
        for problem in problems:
            print(f"  - {problem}")
        return 1

    if args.check:
        if stale:
            print("\nSTALE: " + ", ".join(stale))
            print("Run: python tools/gen_prompt_vocab.py")
            return 1
        print("\nUp to date.")
        return 0

    for path, text in updates.items():
        if text != path.read_text(encoding="utf-8"):
            path.write_text(text, encoding="utf-8")
            print(f"rewrote {path.relative_to(REPO_ROOT)}")
    if not stale:
        print("\nalready correct")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
